config/routes.rb
Rails.application.routes.draw do
  resources :workouts do
  	resources :exercises
  end
  root 'workouts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :workout
end

app/models/workout.rb
class Workout < ApplicationRecord
	has_many :exercices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
	def create
		@workout = Workout.find(params[:workout_id])
		@exercise = Workout.exercises.create(params[:workout].permit(:name, :sets, :reps))
		redirect_to workout_path(@workout)
	end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
	before_action :find_workout, only: [:show, :edit, :update, :destroy]
	
	def index
		@workouts = Workout.all.order("created_at DESC")
	end

	def show
	end

	def new
		@workout = Workout.new
	end

	def create
		@workout = Workout.new(workout_params)
		if @workout.save
			redirect_to @workout
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @workout.update(workout_params)
			redirect_to @workout
		else
			render 'edit'
		end
	end

	def destroy
		@workout.destroy
		redirect_to root_path
	end

	private

	def workout_params
		params.require(:workout).permit(:date, :workout, :mood, :length)
	end

	def find_workout
		@workout = Workout.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_exercises.html.haml
%p= exercise.name
%p= exercise.sets
%p= exercise.reps

app/views/exercises/_form.html.haml
= simple_form_for([@workout, @workout.exercises.buid]) do |f|
	= f.input :name, input_html: {class: "form-control"}
	= f.input :sets, input_html: {class: "form-control"}
	= f.input :reps, input_html: {class: "form-control"}
	%br/
	= f.button :submit

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Séances de sport
	= csrf_meta_tags
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
	= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

%body
	%nav.nabar.navbar-default
		.container
			.navbar-header
				= link_to "Workout Log", root_path, class: "navbar-brand"
			.nav.navbar-nav.navbar-right
				= link_to "Nouvel séance", new_workout_path, class: "navbar navbar_link"
		.container
			= yield

app/views/workouts/_form.html.haml
= simple_form_for(@workout, html: { class: 'form_horizontal'}) do |f|
	= f.input :date, label: "Date"
	= f.input :workout, label: "Qu'allons-nous faire ce jour?", input_html: { class: "form_control"}
	= f.input :mood, label: "Comment l'appréhendes-tu?", input_html: { class: "form_control"}
	= f.input :length, label: "Combien de temps va durer cette séance?", input_html: { class: "form_control"}
	%br/
	= f.button :submit

app/views/workouts/edit.html.haml
%h1 EDITER UNE NOUVELLE SEANCE
= render 'form'
= link_to "Cancel", root_path

app/views/workouts/index.html.haml
%h1 MES SÉANCES DE SPORT

- @workouts.each do |workout|
	%h2= link_to workout.date, workout
	%h3= workout.workout

app/views/workouts/new.html.haml
%h1 AJOUTER UNE NOUVELLE SEANCE
= render 'form'
= link_to "Cancel", root_path

app/views/workouts/show.html.haml
#workout 
	%p= @workout.date
	%p= @workout.workout
	%p= @workout.mood
	%p= @workout.length



= link_to "Retour", root_path 
= link_to "Editer", edit_workout_path(@workout) 
= link_to "Effacer", workout_path(@workout), method: :delete, data: {confirm: "En es-tu sûr ?"}